import type { Metadata } from "next";
import { Fredericka_the_Great } from "next/font/google";
import "./globals.css";
import { NavBar } from "./components/NavBar";
import { CartProvider } from "@/context/CartContext";

const Fredericka = Fredericka_the_Great({
  variable: "--font-fredericka",
  subsets:["latin"],
  weight: "400",
  fallback: ["serif"], // ou ["Times New Roman", "serif"]  
});


export const metadata: Metadata = {
  title: "FrancsBuveurs",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr">
      <body
        className={`${Fredericka.variable} antialiased`}
      >
        <CartProvider>
        <NavBar />
        {children}
        </CartProvider>
      </body>
    </html>
  );
}
