import type { Metadata } from "next";
import { Fredericka_the_Great } from "next/font/google";
import "./globals.css";
import { NavBar } from "./components/NavBar";
import { CartProvider } from "@/context/CartContext";
import { CartIcon } from "./components/CartIcon";
import Footer from "./components/Footer";
import { AuthProvider } from "@/context/AuthContext";
import BackgroundImage from "./components/BgImage";


const Fredericka = Fredericka_the_Great({
  variable: "--font-fredericka",
  subsets:["latin"],
  weight: "400",
  fallback: ["serif"], // ou ["Times New Roman", "serif"]  
});


export const metadata: Metadata = {
  title: "FrancsBuveurs",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr">
      <body
        className={`${Fredericka.variable} antialiased `}
      >
        <AuthProvider>
          <CartProvider>
            <CartIcon />
            <NavBar />
            <BackgroundImage>
              {children}
            </BackgroundImage>
            <Footer/>
          </CartProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
